import * as yup from "yup";

export const initialValues = {
  sub_sistem: "",
  tahap: "",
  amp: "",
  detik: 0,
  mw: 0,
  gardu_induk: "",
  jenis_peralatan: "",
  peralatan: "",
  jenis_peralatan_target: "",
  peralatan_target: "",
  keterangan: "",
  real_ia: 0,
  real_mw: 0,
  real_ols: 0,
  target_ia: 0,
  target_mw: 0,
  target_ols: 0,
  set_ia: 0,
  set_mw: 0,
  set_ols: 0,
  status: "",
  tanggal: new Date(),
};

export const validationSchema = yup.object({
  beban_malam: yup.number().required("This field is required"),
  beban_siang: yup.number().required("This field is required"),
  defense_tahap_id: yup.string().required("This field is required"),
  gardu_induk_id: yup.string().required("This field is required"),
  keterangan: yup.string().required("This field is required"),
  penyulang: yup.string().required("This field is required"),
  penyulang_buka: yup.string().required("This field is required"),
  penyulang_kw: yup.number().required("This field is required"),
  penyulang_tutup: yup.string().required("This field is required"),
  set: yup.number().required("This field is required"),
  status: yup.string().required("This field is required"),
  sub_sistem_id: yup.string().required("This field is required"),
  tanggal: yup.string().required("This field is required"),
  trafo_id: yup.string().required("This field is required"),
  ufr_kw: yup.number().required("This field is required"),
  ufr_masuk: yup.string().required("This field is required"),
  ufr_trip: yup.string().required("This field is required"),
});
