import * as yup from 'yup'

export const optionJenisPeralatan = [
  { label: "IBT", value: "ibt" },
  { label: "Pembangkit", value: "pembangkit" },
  { label: "Trafo", value: "trafo" },
  { label: "Busbar", value: "busbar" },
  { label: "Penghantar", value: "penghantar" },
  { label: "Reaktor", value: "reaktor" },
]

export const initialValues = {
  akibat: "",
  announciator: "",
  arus: "",
  beban: "",
  cuaca: "",
  dfr: "",
  fl: "",
  gangguan_jenis_id: "",
  gardu_induk_id: "",
  gensum: "",
  jenis_peralatan: "",
  la: "",
  lain: "",
  lap: "",
  penyebab: "",
  peralatan_id: "",
  pqm: "",
  rele: "",
  siap_op: "",
  sld: "",
  buka: new Date(),
  pmt: new Date(),
  reclose: new Date(),
  sms_kinerja: new Date(),
  tanggal: new Date(),
  trip: new Date(),
  tutup: new Date(),
  vaisala: ""
}

export const validationSchema = yup.object({
  akibat: yup.string().required('This field is required'),
  announciator: yup.string().required('This field is required'),
  arus: yup.string().required('This field is required'),
  beban: yup.string().required('This field is required'),
  buka: yup.string().required('This field is required'),
  cuaca: yup.string().required('This field is required'),
  dfr: yup.string().required('This field is required'),
  fl: yup.string().required('This field is required'),
  gangguan_jenis_id: yup.string().required('This field is required'),
  gardu_induk_id: yup.string().required('This field is required'),
  gensum: yup.string().required('This field is required'),
  jenis_peralatan: yup.string().required('This field is required'),
  la: yup.string().required('This field is required'),
  lain: yup.string().required('This field is required'),
  lap: yup.string().required('This field is required'),
  penyebab: yup.string().required('This field is required'),
  peralatan_id: yup.string().required('This field is required'),
  pmt: yup.string().required('This field is required'),
  pqm: yup.string().required('This field is required'),
  reclose: yup.string().required('This field is required'),
  rele: yup.string().required('This field is required'),
  siap_op: yup.string().required('This field is required'),
  sld: yup.string().required('This field is required'),
  sms_kinerja: yup.string().required('This field is required'),
  tanggal: yup.string().required('This field is required'),
  trip: yup.string().required('This field is required'),
  tutup: yup.string().required('This field is required'),
  vaisala: yup.string().required('This field is required')
})